### PR TITLE
switch to use of Mono helpers (closes #3)

### LINKED ISSUE #3: Autosplitter's splitting is acting weird again
It's been reported that the autosplitter has split at the beginning of maps (like in Brionac's latest LTE run [here](https://youtu.be/HI3hJX3OgTU)), and also it's apparently been splitting at the start of maps when Tribow was using a custom playlist for Minute Assault runs.

Haven't done any debugging on this yet so currently not sure if this is problem with just the code, or if maybe the pointers are fucked again.

### PR DESCRIPTION
**Pull request by ero-qt**
Finally, the PR to merge all changes into master.

### CODE REVIEW

**Comment by ero-qt** [comment]
Make sure to re-approve the changes so that I can open a PR to [`LiveSplit.AutoSplitters.xml`](https://github.com/LiveSplit/LiveSplit.AutoSplitters/blob/master/LiveSplit.AutoSplitters.xml) adding the Mono classes.

**Review by Tiyenti — APPROVED** [review]
Alright, seems like everything's working as expected now. Gonna merge.

**Comment by ero-qt** [comment]
As mentioned [here](https://github.com/Tiyenti/distance.asl/pull/5#issuecomment-1026466868), [the PR to `LiveSplit.AutoSplitters.xml`](https://github.com/LiveSplit/LiveSplit.AutoSplitters/pull/665) must also be merged such that the users are provided with the C# classes.

**Comment by ero-qt** [comment]
Done and done.

**Pull request merged**
